---

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "chatbot:0.11"
    container_name: streamlit_front
    restart: always
    ports:
      - "127.0.0.1:8501:8501"
    networks:
      - backend

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8090:80'
      # - '443:443'
      - '8081:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
