[global]
showWarningOnDirectExecution = true

[logger]
level = "info"

[runner]
magicEnabled = true

[server]
# folderWatchBlacklist removed in Streamlit 1.46+
headless = true
liveSave = false
runOnSave = false
port = 8501
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501
